### ISSUE TITLE
8051 CPU Project

### ISSUE THREAD

**Issue by FlorianFaltin** [microchip-ung/mesa#5]
Hello MESA developers.

I had used MESA previously to generate the code for a VSC7429 (MIPS-based) ethernet switch board design.
Customization was quite a challenge, but in the end it worked fine.

Now I have a new challenge with a VSC7511 (8051-based) ethernet switch board.
According to the "Supported HW" list that switch is also supported by MESA.
I struggle already in the beginning - I cannot create a 8051-based project. I neither find a u-boot release for it (there is an ocelot u-boot, but it is in the mipsel package - so I guess for VSC7513/VSC7514 switches, which are MIPS-based).

Is the VSC7511 really supported by MESA? How to create a project for this switch?

Thanks,
Florian
Elma Electronic GmbH

**Comment by allannielsen** [comment]
Hi,
VSC7511 is only supported by MESA when using an external CPU (over SPI or PCIe). If you want to use the embedded 8051, then you should have a look at https://github.com/microchip-ung/ocelot-vsc6825 instead.
/Allan
