### ISSUE TITLE
Not  Able to compile/run the examples in linux machine

### ISSUE THREAD

**Issue by vigneshv88hcl** [microchip-ung/mesa#6]
We are using VSC8254 Microsemi PHY (10g) ,for better understanding e tried to run the ./build_10g_phy_alone.sh and also few other examples listed out in the folder mesa-2021.06/phy_demo_appl.
We get so many errors/warnings. Listed below a few,

n file included from ../include/vtss_api.h:20,
                 from appl/vtss_appl_board_viper_eval.c:13:
../include/vtss_init_api.h:454:5: error: unknown type name ‘vtss_gpio_func_info_get_t’
  454 |     vtss_gpio_func_info_get_t gpio_func_info_get;       /**< GPIO functionallity information get callout function */
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
appl/vtss_appl_board_viper_eval.c: In function ‘port_interface’:
appl/vtss_appl_board_viper_eval.c:29:60: warning: unused parameter ‘port_no’ [-Wunused-parameter]
   29 | static vtss_port_interface_t port_interface(vtss_port_no_t port_no)
      |                                             ~~~~~~~~~~~~~~~^~~~~~~
appl/vtss_appl_board_viper_eval.c: In function ‘viper_phy_pre_reset’:
appl/vtss_appl_board_viper_eval.c:38:10: warning: implicit declaration of function ‘vtss_phy_pre_reset’; did you mean ‘vtss_phy_10g_reset’? [-Wimplicit-function-declaration]
   38 |     rc = vtss_phy_pre_reset (NULL, 0);
      |          ^~~~~~~~~~~~~~~~~~
      |          vtss_phy_10g_reset
appl/vtss_appl_board_viper_eval.c:37:15: warning: variable ‘rc’ set but not used [-Wunused-but-set-variable]
   37 |     vtss_rc   rc;
      |               ^~
appl/vtss_appl_board_viper_eval.c: In function ‘viper_phy_post_reset’:
appl/vtss_appl_board_viper_eval.c:45:13: warning: implicit declaration of function ‘vtss_phy_post_reset’; did you mean ‘viper_phy_post_reset’? [-Wimplicit-function-declaration]
   45 |     return (vtss_phy_post_reset (NULL, 0));
      |             ^~~~~~~~~~~~~~~~~~~
      |             viper_phy_post_reset
appl/vtss_appl_board_viper_eval.c: In function ‘miim_read’:
appl/vtss_appl_board_viper_eval.c:117:40: warning: unused parameter ‘inst’ [-Wunused-parameter]
  117 | vtss_rc miim_read(const vtss_inst_t    inst,
      |                   ~~~~~~~~~~~~~~~~~~~~~^~~~
appl/vtss_appl_board_viper_eval.c: In function ‘miim_write’:
appl/vtss_appl_board_viper_eval.c:146:41: warning: unused parameter ‘inst’ [-Wunused-parameter]
  146 | vtss_rc miim_write(const vtss_inst_t    inst,
      |                    ~~~~~~~~~~~~~~~~~~~~~^~~~
In file included from appl/vtss_appl_board_viper_eval.c:15:
appl/vtss_appl_board_viper_eval.c: In function ‘mmd_read’:
appl/vtss_appl_board_viper_eval.c:168:9: warning: format ‘%X’ expects a matching ‘unsigned int’ argument [-Wformat=]
  168 |     T_N("mmd_read port_no = %d, mmd = %d addr = %d, value = 0x%X", port_no, mmd, addr);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
appl/vtss_appl.h:68:230: note: in definition of macro ‘T_N’
   68 | _callout_trace_printf(VTSS_APPL_TRACE_LAYER, VTSS_APPL_TRACE_GROUP, VTSS_TRACE_LEVEL_NOISE, __FILE__, __LINE__, __FUNCTION__, __VA_ARGS__); }
      |                                                                                                                               ^~~~~~~~~~~

appl/vtss_appl_board_viper_eval.c:168:64: note: format string is defined here
  168 |     T_N("mmd_read port_no = %d, mmd = %d addr = %d, value = 0x%X", port_no, mmd, addr);
      |                                                               ~^
      |                                                                |
      |                                                                unsigned int
appl/vtss_appl_board_viper_eval.c:161:39: warning: unused parameter ‘inst’ [-Wunused-parameter]
  161 | vtss_rc mmd_read(const vtss_inst_t    inst,
      |                  ~~~~~~~~~~~~~~~~~~~~~^~~~
appl/vtss_appl_board_viper_eval.c:165:54: warning: unused parameter ‘value’ [-Wunused-parameter]
  165 |                         u16                   *const value)
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
In file included from appl/vtss_appl_board_viper_eval.c:15:
appl/vtss_appl_board_viper_eval.c: In function ‘mmd_write’:
appl/vtss_appl_board_viper_eval.c:179:9: warning: format ‘%X’ expects a matching ‘unsigned int’ argument [-Wformat=]
  179 |     T_N("mmd_write port_no = %d, mmd = %d addr = %d, value = 0x%X", port_no, addr, data);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
appl/vtss_appl.h:68:230: note: in definition of macro ‘T_N’
   68 | _callout_trace_printf(VTSS_APPL_TRACE_LAYER, VTSS_APPL_TRACE_GROUP, VTSS_TRACE_LEVEL_NOISE, __FILE__, __LINE__, __FUNCTION__, __VA_ARGS__); }
      |                                                                                                                               ^~~~~~~~~~~

appl/vtss_appl_board_viper_eval.c:179:65: note: format string is defined here
  179 |     T_N("mmd_write port_no = %d, mmd = %d addr = %d, value = 0x%X", port_no, addr, data);
      |                                                                ~^
      |                                                                 |
      |                                                                 unsigned int
appl/vtss_appl_board_viper_eval.c:172:40: warning: unused parameter ‘inst’ [-Wunused-parameter]
  172 | vtss_rc mmd_write(const vtss_inst_t    inst,
      |                   ~~~~~~~~~~~~~~~~~~~~~^~~~
appl/vtss_appl_board_viper_eval.c:174:48: warning: unused parameter ‘mmd’ [-Wunused-parameter]
  174 |                          const u8              mmd,
      |                          ~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from ../include/vtss_api.h:14,
                 from appl/vtss_appl.c:5:
../include/vtss/api/options.h:602: warning: "VTSS_CHIP_10G_PHY" redefined
  602 | #define VTSS_CHIP_10G_PHY                      /**< 10Gb 848x Phy API  */
      | 
<command-line>: note: this is the location of the previous definition
In file included from ../include/vtss_api.h:20,
                 from appl/vtss_appl.c:5:
../include/vtss_init_api.h:454:5: error: unknown type name ‘vtss_gpio_func_info_get_t’
  454 |     vtss_gpio_func_info_get_t gpio_func_info_get;       /**< GPIO functionallity information get callout function */
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/vtss_api.h:14,
                 from appl/vtss_appl_cli.c:5:
../include/vtss/api/options.h:602: warning: "VTSS_CHIP_10G_PHY" redefined
  602 | #define VTSS_CHIP_10G_PHY                      /**< 10Gb 848x Phy API  */
      | 
<command-line>: note: this is the location of the previous definition
In file included from ../include/vtss_api.h:20,
                 from appl/vtss_appl_cli.c:5:
../include/vtss_init_api.h:454:5: error: unknown type name ‘vtss_gpio_func_info_get_t’
  454 |     vtss_gpio_func_info_get_t gpio_func_info_get;       /**< GPIO functionallity information get callout function */

_We also tried to make -f Makefile_10g but its showing_ 
make: *** No rule to make target 'base/ail/vtss_api.c', needed by 'vtss_api.o'.  Stop.

**Could we get some clarity on this?**

**Comment by allannielsen** [comment]
Hi,
At the moment the github page is used for distributing the release including the entire change log.
Please raise your support requests here: https://microchipsupport.force.com/s/article/How-to-submit-a-case
/Allan
